title: Sunrise Blog
subtitle: blog
description: >- # this means to ignore newlines until "baseurl:"
  This is the demo site for a Jekyll theme version of
  HTML5 UP's sleek, responsive site template Prologue.
author: sunrise
email: 1452474095@qq.com
avatar: assets/images/avatar.jpg

# You'll want to customize url and baseurl for your own site:
baseurl: "/sunrisexl" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
facebook_url:
github_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Google Analytics Tracking ID goes here:
google_analytics:

# The following settings are NECESSARY for the Prologue theme to run:
# theme: jekyll-theme-prologue
collections: [sections]
